### PR TITLE
Add configurable base path

### PR DESCRIPTION
**Pull request by shreelakshmijoshi**
- Added configurable base paths in all the verticles of config-dev 
- Changed the following files : [here](https://github.com/datakaveri/iudx-gis-interface/pull/78/commits/5d45843e6c68d5ac049d80feb1aa9aa0868147a2)
  -  ApiServerVerticle.java
  -  AuthHandler.java
  - apiserver/util/Constants.java
  - JwtAuthenticationServiceImpl.java
  - JwtAuthServiceImplTest.java
  - metering/util/QueryBuilder.java
  - MeteringVerticle.java
  - MeteringServiceImpl.java
  - AuthHandlerTest.java
  
To Do : 
- [x] Unmount [this](https://github.com/datakaveri/iudx-gis-interface/pull/78/commits/c5a2da2f674861f2d3aa468a56c3b9046ff7a3de) from the compose
- [x] Adding `commonConfig` in the CI config
```
"commonConfig" : {
    "dxApiBasePath": "/ngsi-ld/v1",
    "adminBasePath": "/admin/gis/serverInfo"
  },
```

### CODE REVIEW

**Comment by karun-singh** [comment]
ok to test

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Pull request merged**
